import Head from 'next/head';
import ColorBox from '../src/components/colorbox/ColorBox';
import MakeSet from '../src/components/makeSet/MakeSet';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MakeSet />
      <ColorBox />
    </div>
  );
}
